apiVersion: v1
kind: ConfigMap
metadata:
  name: sms-backend-config
  namespace: sms-production
data:
  NODE_ENV: "production"
  PORT: "3001"
  API_PREFIX: "/api"
  API_VERSION: "v1"
  CORS_ORIGIN: "https://sms.yourdomain.com"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
  LOG_LEVEL: "info"
  REDIS_URL: "redis://sms-redis:6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sms-frontend-config
  namespace: sms-production
data:
  REACT_APP_API_URL: "https://api.sms.yourdomain.com/api/v1"
  REACT_APP_ENVIRONMENT: "production"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sms-nextjs-config
  namespace: sms-production
data:
  NEXT_PUBLIC_API_URL: "https://api.sms.yourdomain.com/api/v1"
  NEXT_PUBLIC_ENVIRONMENT: "production"
  NEXTAUTH_URL: "https://sms.yourdomain.com"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: sms-production
data:
  POSTGRES_DB: "sms_production"
  POSTGRES_USER: "sms_user"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: sms-production
data:
  redis.conf: |
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    save 900 1
    save 300 10
    save 60 10000
    appendonly yes
    appendfsync everysec
