apiVersion: v1
kind: Secret
metadata:
  name: sms-backend-secrets
  namespace: sms-production
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  DATABASE_URL: cG9zdGdyZXNxbDovL3Ntc191c2VyOnNtc19wYXNzd29yZEBzbXMtcG9zdGdyZXM6NTQzMi9zbXNfcHJvZHVjdGlvbg==
  JWT_SECRET: eW91ci1wcm9kdWN0aW9uLWp3dC1zZWNyZXQtY2hhbmdlLXRoaXM=
  ENCRYPTION_KEY: eW91ci1lbmNyeXB0aW9uLWtleS1jaGFuZ2UtdGhpcw==
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: sms-production
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  POSTGRES_PASSWORD: c21zX3Bhc3N3b3Jk
---
apiVersion: v1
kind: Secret
metadata:
  name: sms-payment-secrets
  namespace: sms-production
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  STRIPE_SECRET_KEY: c2tfdGVzdF95b3VyX3N0cmlwZV9zZWNyZXRfa2V5
  STRIPE_WEBHOOK_SECRET: d2hzZWNfeW91cl93ZWJob29rX3NlY3JldA==
  PAYPAL_CLIENT_ID: eW91cl9wYXlwYWxfY2xpZW50X2lk
  PAYPAL_CLIENT_SECRET: eW91cl9wYXlwYWxfY2xpZW50X3NlY3JldA==
---
apiVersion: v1
kind: Secret
metadata:
  name: sms-email-secrets
  namespace: sms-production
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  SMTP_HOST: c210cC5nb29nbGUuY29t
  SMTP_PORT: NTg3
  SMTP_USER: eW91ci1lbWFpbEBnbWFpbC5jb20=
  SMTP_PASSWORD: eW91ci1lbWFpbC1wYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: sms-monitoring-secrets
  namespace: sms-production
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  GRAFANA_ADMIN_PASSWORD: YWRtaW5fcGFzc3dvcmQ=
  PROMETHEUS_PASSWORD: cHJvbWV0aGV1c19wYXNzd29yZA==
